[package]
name = "egor00f/code-editor"

description = "Code editor in game"

version = "0.1.0"

registry = "https://github.com/UpliftGames/wally-index"

realm = "shared"

license = "MIT"

repository = "https://github/Ukuroks-Games/roblox-code-editor"

authors = ["Egor00f <velikiydolbayeb@gmail.com>"]

exclude = ["code-editor.rbxl"]

private = false

[dependencies]

[server-dependencies]


[dev-dependencies]

